#!/usr/bin/env bash
# Installs nginx server

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw 'Nginx HTTP'

# Create a simple HTML file with "Hello World!"
echo "<html><head><title>Hello World!</title></head><body>Hello World!</body></html>" | sudo tee /var/www/html/index.html

sudo nginx -t

sudo service nginx  restart
sudo service nginx reload
